[package]
name = "renderer"
version = "0.1.0"
authors = ["Evan Brass <evan-brass@protonmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
panic = 'abort'
debug = true

[profile.dev]
panic = 'abort'

[dependencies]
wasm-bindgen = "0.2"
